### ISSUE TITLE
Unify The Enigma Community

### ISSUE THREAD

**Issue by moonstash** [secretnodes/secretnodes.org#13]
**Proposal**
I propose we collectively find a way to achieve a token swap so we can unify the Enigma Community. We already have a diverse set of people ready to build on enigma, participate in governance, stake, and run nodes from all around the world. I welcome everyone interested in this to further discuss how it can be achieved here.

**Comment by dbriggsie** [comment]
This is definitely the best way forward for the community which has been supporting Enigma from the start and continually grown into what we have today. 
Its Paramount for swaps to take place.

**Comment by CavemanCrypto** [comment]
It is vital that we as a community move swiftly to unify, but also decentralize. Facilitating a token swap is the only way to make this happen and bridge the ENG community & token holders over to Enigmachain and use of SCRT in the ecosystem. What are people thinking in terms of a ratio for the swap? SCRT currently has a supply ~50M. ENG has a total supply of 150M. We know that 75M ENG in in circulation, but  it is unclear what amount of the Enigma team's allocated tokens are unlocked. It is also unclear how much of the 50M SCRT the team holds unless I am mistaken. DO we exchange at a rate of 1 ENG: 1 SCRT with the assumption that the team holdings have transferred over to the 50M SCRT? Who has other suggestions?

**Comment by AndrewChriss** [comment]
1:1 swap

**Comment by FishmanL** [comment]
FROM TG: RE: 1:1 swaps

Leor Fishman, [17.02.20 06:30]
Also — for people worrying about inflation, just have the validation team pass in the initial proposal that scrt amounts are autopegged to total amounts of eng (which you can verify by having one or two validators be lite eth nodes)

Leor Fishman, [17.02.20 06:31]
heck, you could even preserve public keys for scrt assuming cosmos uses the same ecdsa structure as eth

Leor Fishman, [17.02.20 06:31]
and then there's no 'time limit' on swapping

Leor Fishman, [17.02.20 06:32]
just 'whenever you want to swap, you swap, and whichever validator nodes are in charge of pegging scrt to eng see how much you have'

Leor Fishman, [17.02.20 06:35]
heck, cosmos is literally built for this, lol

**Comment by FishmanL** [comment]
Also, team holdings _definitely haven't_ moved over to SCRT and are still in ENG, otherwise the SEC would eat them alive.

**Comment by FishmanL** [comment]
https://github.com/jpthor/cosmos-swap/tree/master likely a good starting point

**Comment by MrGarbonzo** [comment]
Let's start the process of getting a 1:1 swap of eng:scrt 

It's the best wayy forward to unite the community and to create a secure/functional network

**Comment by FishmanL** [comment]
https://github.com/enigmampc/enigmachain/tree/2c14ad2ed26299f98f661cf2c15d4474d64a37dd/x/tokenswap well won't you look at that

**Comment by FishmanL** [comment]
https://github.com/enigmampc/enigmachain/blob/2c14ad2ed26299f98f661cf2c15d4474d64a37dd/x/tokenswap/keeper/keeper.go in particular this code has...helpful things

**Comment by moonstash** [comment]
@FishmanL This proposal is exclusively about how to get a swap done it is NOT about inflation. It's important that a token swap happens so token holders can make their own proposals and support what they want to see changed, explain why, and have the community agree. The very first step in that process is getting the token swap done.

**Comment by moonstash** [comment]
We've also determined that there is no code from the enigma team capable of doing this swap so as it currently stands it looks like we will have to get it built and funded through the community pool funds on the enigma protocol.

**Comment by FishmanL** [comment]
There exists no code from the team that performs the swap, i was merely linking something that served as architecture/skeletal structure for such code.

**Comment by CarterLWoetzel** [comment]
I agree with moonstach & FishmanL the best steps are to move forward with the swap by creating the code required, supported by community funding. I would propose we hold an open community call to discuss this proposal, and that a comprehensive document would be written up for the steps moving forward for the entire community to see.

**Comment by ENG2020** [comment]
I am in agreement that we the community create a 1:1 swap of ENG to SCRT for the good of the network.

**Comment by AndrewChriss** [comment]
absolutely no inflation

**Comment by moonstash** [comment]
@AndrewChriss Thanks for your comment but this proposal doesn't cover inflation. This proposal is about a token swap.

**Comment by AndrewChriss** [comment]
Yes, I support a token swap of 1:1

**Comment by CosmicCollusion** [comment]
1:1 is fine. Any ratio is really, assuming the  distribution of funds on the current enigma token is the same moving onto the main net.

Will need to wait and gain some clarification on what the current token supply on main net is and how it was distributed first though.

**Comment by CASD-GM** [comment]
I support a token swap of 1:1

**Comment by Carloscrypto2017** [comment]
I support 1:1 swap

**Comment by JC-2140** [comment]
1:1 swap

**Comment by econguru** [comment]
I propose a 20% initial inflation rate to support the stabilization of the network in it's infancy.

**Comment by M0lekule21** [comment]
A token swap should only be conducted when and if “we” the community know clearly and concisely the original token economics of ENG will be preserved if a swap is universally agreed upon firstly. Myself and many others believe that swapping into a new token without knowing who issued these SCRT, nor knowing the allocations of, wallets, or future minting Ie; inflation rate, I recommend we do not conduct a swap until these and other questions are answered by the ‘issuer’. Further more a reason to not blindly swap into SCRT is we have no Audit issued for this code yet. Enigma, the team, has gone on record setting rules for a master node program that required accumulating ENG tokens. For these reasons I firmly recommend no swap until this request is amended to include more detailed language and intent.

**Comment by Zedfromthedead** [comment]
You are a fucking nutjob Ian Dixon. Nobody should trust this loser to swap their tokens. He is just as trustworthy as the hackers who stole half a million dollars from the Enigma ICO. The Enigma team are complicit in everything that is going on right now. If they don't think what they are doing is illegal then they are naive. If they don't think this will follow them wherever they go then they are deluded. If they don't think they will face the consequences then they are stupid. Don't support a token swap. There is no basis for this token swap except for the ramblings of one nutcase named Ian Dixon.

**Comment by Zedfromthedead** [comment]
Like my comment if you vote AGAINST a token swap.

**Comment by moonstash** [comment]
@Zedfromthedead comment was deleted for personally attacking. Feel free to say you do not support a token swap if you don't support one.

**Comment by uxt-exe** [comment]
I do not support a "token swap" since it is not mandated by the team. You'd be exchanging your ENG for a third party, unofficial coin.  The intent from those in support of the "swap" is likely to make people make this mistake and divide the community. It is a hostile takeover of Enigma fueled by confusion.  There is NO indication the "mainnet" is legitimate, sanctioned, or permanent. It would be very unlike the team at Enigma to totally ditch their plan for the Genesis Game and roll with a unannounced but active mainnet that profited some inner circle while refusing to speak on the topic.

Those engaged in "swaps" or on board with "swaps" at this stage: do not be angry when you find yourself holding some worthless defunct token.  The community has no responsibility to ease your loss or compromise. It is your choice to follow fear instead of doing literally nothing and waiting for official guidance.  Do not be confused by technical details you don't understand and rush your decision making.

And yes, cryptocurrency is permissionless, so sanctioned is a bit of a confusing topic.  But these projects live and die by the efforts of the founding team and developers. And they won't be working for free on a separatist project so enjoy lagging security fixes and features.

**Comment by elevendayempire** [comment]
Now that the Enigma team has released the news of the mainnet launch and SEC settlement, I support a 1:1 swap from ENG to SCRT.

**Comment by j609** [comment]
Hi Enigma community,

In light of recent developments, I feel the best option available to existing token holders is to support a 1:1 token swap of ENG to SCRT.

Undertaking a 1:1 swap is the best means of protecting community members and ensuring long-term network growth.

**Comment by shathil** [comment]
I support a 1:1 swap from ENG to SCRT.

**Comment by uxt-exe** [comment]
> I do not support a "token swap" since it is not mandated by the team. You'd be exchanging your ENG for a third party, unofficial coin. The intent from those in support of the "swap" is likely to make people make this mistake and divide the community. It is a hostile takeover of Enigma fueled by confusion. There is NO indication the "mainnet" is legitimate, sanctioned, or permanent. It would be very unlike the team at Enigma to totally ditch their plan for the Genesis Game and roll with a unannounced but active mainnet that profited some inner circle while refusing to speak on the topic.
> 
> Those engaged in "swaps" or on board with "swaps" at this stage: do not be angry when you find yourself holding some worthless defunct token. The community has no responsibility to ease your loss or compromise. It is your choice to follow fear instead of doing literally nothing and waiting for official guidance. Do not be confused by technical details you don't understand and rush your decision making.
> 
> And yes, cryptocurrency is permissionless, so sanctioned is a bit of a confusing topic. But these projects live and die by the efforts of the founding team and developers. And they won't be working for free on a separatist project so enjoy lagging security fixes and features.

well, I was very wrong.  I stand by my decision that it was a bad idea without Enigma's blessing.  However given all the official information that has been discussed today, I think it is in the best interest of everyone to do a 1:1 swap from ENG to SCRT.  Furthermore, this decision is solely in the hands of the validators. This is a distributed network, now.  Please do the right thing - if any development is required to facilitate the swap please feel free to ping me and I'll contribute some time & energy.

**Comment by FishmanL** [comment]
I'd support a 1:1 swap -- _plus_ a burn of all unstaked scrt at the time of the swap's beginning to mostly even out the supply without penalizing the validators!

**Comment by shahh** [comment]
1:1 swap from ENG to SCRT

**Comment by patreides2** [comment]
I support a 1:1 swap ENG to SCRT

**Comment by mohammedpatla** [comment]
Same would love to see 1:1 SWAP here.

**Comment by luigi1111** [comment]
@FishmanL that idea might work; not sure if team would be able to stake their tokens to prevent them from being wiped out, or if you plan to allow team's ENG to swap?

IMO a decentralized network isn't really possible if it starts out with around 35-40% in the hands of the team. I think around half that is the high end of what should be expected, with less preferred.

If we are leaving SCRT distribution as is, I would like to see a 1:2-5x swap rate. If I had to pick a number, I'd choose 1:3 ENG:SCRT I think, with team's ENG not on the swappable list.

**Comment by moonstash** [comment]
@luigi1111 Thank you for respectfully voicing your thoughts here. I seriously appreciate it. Even if I do not agree with all of your terms.

**Comment by uxt-exe** [comment]
> @FishmanL that idea might work; not sure if team would be able to stake their tokens to prevent them from being wiped out, or if you plan to allow team's ENG to swap?
> 
> IMO a decentralized network _with built-in governance_ isn't really possible if it starts out with around 35-40% in the hands of the team. I think around half that is the high end of what should be expected, with less preferred.
> 
> If we are leaving SCRT distribution as is, I would like to see a 1:2-5x swap rate. If I had to pick a number, I'd choose 1:3 ENG:SCRT I think, with team's ENG not on the swappable list.

I would also prefer a ratio like 1:2 or 1:3, however more than anything I would prefer reaching consensus (which seems to be currently forming around 1:1).  What I definitely want to avoid is infighting in this already chaotic time.

**Comment by vinnya54** [comment]
Been following this project since 12/2017. Absolutely in favor of a swap!

**Comment by nonoreprep** [comment]
I seriously don't get what is going on. What will happen to ENG? Is this token dead?
Mainnet is running on cosmos but it uses SCRT?

**Comment by moonstash** [comment]
@nonoreprep SCRT is a new token which powers the enigma mainnet. You must swap ENG for SCRT to participate in the engima protocol. Please research outside of this post and come back with your opinion. Thank you.

**Comment by hakki-lab** [comment]
I support the swap, from ENG to SCRT

**Comment by Steve9898** [comment]
been in it since the beginning so I support this swap from ENG to SCRT

**Comment by cryptojoe12** [comment]
I support 1 of two scenarios for a swap:

1. A ratio 1:2 to account for the amount that validators have profited prior to the swap

2. Slashing all of validator rewards prior to the swap 

I also support the swap if the validators can agree to maintaining the inflation rate at 0 until the Enigma community has fully transitioned over to cosmos SCRT and has been able to contribute to voting for the inflation rate.

**Comment by jimmfarley** [comment]
I support a swap with input on fairness of the specifics from a 3rd party org, for instance one that has performed swaps in the past.

**Comment by Rob0071** [comment]
1) 
1 ENG to 1 SCRT swap with fair distribution of current node runners 
- Ensure fair distribution of ENG holder to SCRT
*********************************************************************
2) 
I recommend that the Co-Founders cannot swap until at least 15% of the ENG tokens have been swapped for SCRT.

**Comment by Cryptofzb** [comment]
I've been carefully reading different documents about the new economic model model for Enigma. With the official news from the team, I support a 1:1 swap from ENG to SCRT.

Greetings from a top 100 ENG holder.

**Comment by econguru** [comment]
I support a 1:1 swap of ENG to SCRT

**Comment by DevFind** [comment]
It would make sense to me that supply is capped at a lower amount than existing ENG. Inflation set to 0 at start and decided only after a swap has occurred. 

Then we should incentivise existing (dissapointed) token holders by providing a swap that ensures a greater % of total tokens than they previously held. 

e.g. max supply at 125 mil with a swap of 1:1.5. Existing circulation of 75 mil would then hold 112.5 mil tokens with the remaining 12.5 mil for network activities/team.

I would support a 1:1.5 swap of ENG to SCRT with a total fixed supply of 125 million SCRT

**Comment by theKatzPajamas** [comment]
Been an Enigma supporter since 2018.  I'm gonna echo the comments supporting a swap with the condition that it's done in such a way that ENG holders don't get screwed from inflation and rewards that have gone to the main net validators over the last week.  

I'm not familiar with the tokenomics or how many SCRT tokens have been issued to those nodes so I can't suggest what I think a fair ratio would be but I think it would be immoral to essentially give those people free tokens at the expense of existing ENG holders

**Comment by erikb13** [comment]
I support the swap from ENG to SCRT.

**Comment by CavemanCrypto** [comment]
> Like my comment if you vote AGAINST a token swap.

NO Zed. Why would people want to hold ENG if it is not used in the network?

**Comment by theKatzPajamas** [comment]
The only fair solution should be if before main net you had 1% of the tokens then you get 1% of the tokens on the main net.

**Comment by theKatzPajamas** [comment]
I don't know what the specifics are for ENG and SCRT in terms of number of tokens but  someone who had 1% of the total ENG should also have 1% of the total SCRT at the exchange date.  That's the only way to ensure that ENG holders don't get screwed.

**Comment by 4cbe19** [comment]
Given that the current supply of SCRT is ~ 50 million, I support a 1:1 swap of the ENG circulating supply (75 million ENG), resulting a total supply of 125 million SCRT + validator rewards.

**Comment by jingjang99** [comment]
I support a 1:1 swap. There's much more to be said on the detail in time, but at this point it's important to keep things simple and not risk muddying the waters, so it's a +1 to the 1:1 ratio from me.

**Comment by fakecryptoman** [comment]
I don't know the number of SCRT tokens but I support a meaningful and maybe 1:1 ENG:SCRT swap but at the end the percentage value of the ENG holder should have the same percentage of SCRT after the swap. The swap ratio depends on the number of SCRT tokens but in any case I support the swap!

**Comment by ajcronk** [comment]
I see the genesis distribution of SCRT here.  How was this chosen?

https://github.com/enigmampc/enigmachain/blob/5af96d4f493ec849fa3e122fe08428f5980edbad/enigma-1-genesis.json

**Comment by Codonyat** [comment]
Yes to token swap and the sooner the better. 1-to-1 is fair imo.

**Comment by dkfeeld** [comment]
I support the proposal as long as we don't get diluted!

**Comment by Russ1244** [comment]
Support the token swap idea.  In this hypothetical swap, the SCRT should be proportional to what the ENG holder owns relative to the total ENG supply.  So it depends on the SCRT supply and where the current 50 million SCRT came from.  

Do not support anything where that 50 million came out of nowhere/nothing

**Comment by eddiedunn** [comment]
I support a token swap. No dilution would be ideal.

**Comment by kcbox00** [comment]
Support 1:1 swap. 100-125M fixed supply.

**Comment by CryptoGrizzly** [comment]
I support a 1:1 SWAP from ENG to SCRT. The community must come together! Inflation and other functions can be discussed by voting after the swap (my opinion)

**Comment by plinkfuture** [comment]
1 ENG -> ? 1.5-3 SCRT
(A swap that achieves a more decentralized token distribution from team/vc to community.  Can locked ENG(if any) be burned?

Inflation set=0 & decided after swap(what effect will inflation have on price)?

**Comment by OldStalin** [comment]
I support the swap from ENG to SCRT. I since 2017 I support the project and the community

**Comment by windkostya** [comment]
I support a token swap. No dilution would be ideal.

**Comment by phucjackson2106** [comment]
I support a token swap from ENG to SCRT with the ratio 1:1.

**Comment by baedrik** [comment]
I think that the genesis game should still take place, just on SCRT testnet.  I understand the importance of getting the new main net up and running asap, but now that is done, the genesis game should still take place as planned.  
They can create a form that requires you to sign a transaction from the ETH address that had enough ENG at the time of snapshot to participate in the game.  They can verify that you had at least 25k ENG average during their snapshot and then send you testnet SCRT so that you can run a testnet validator.  Then select winners as originially intended with the genesis game.
If a current validator does not win the genesis game, they won't get to be a validator, but can still keep the mainnet SCRT they have been gifted as a thank you for being there during the ENG testnet and early SCRT mainnet.  As you recall, the reason node selection was changed from needing to have at least 25k ENG to needing to have that amount AND winning the genesis game was because the game would ensure that the most reliable validators are chosen.  So if a current validator proves to not be one of the most reliable, the network benefits by having them replaced, but for the work they have done, they still get to keep all the SCRT they have been awarded.
Running the genesis game as planned will help restore trust in the team and prove that even when things out of their control happen, they are willing to do what IS in their control to keep their word.  If they choose not to do what is in their control, then it does raise suspicion that this is a convenient way to hand pick who they want as validators outside the rules of the genesis game.

**Comment by alexwestest** [comment]
Swap 1: 1, I think is fair.

**Comment by silkyjohnson1** [comment]
Swap this motherfucker

**Comment by salix27tz** [comment]
I would like 1:1 swap.

**Comment by PresenceNumerique** [comment]
One has to consider incentives for the community to support this nascent network.
I would thus support:
- A 1:1.5 ENG to SCRT swap.
- No inflation for 3 months, beginning when swap functionality available.

**Comment by Igoryanich** [comment]
I support the swap. 
1:1

**Comment by tommivk** [comment]
I support a token swap from ENG to SCRT.

**Comment by Kiwieng** [comment]
I support a token swap from ENG to SCRT. Best option.

**Comment by shiro-hh** [comment]
I support a token swap
ENG to SCRT 1:1,5

**Comment by Nikopolfernes** [comment]
I support a 1:1 swap from ENG to SCRT. 125M supply. it's less than it was (150M)

**Comment by jshiller** [comment]
I see the proposal has passed. Does that mean a swap is definitely happening?

https://explorer.mainnet.enigma.co/proposals/2

**Comment by moonstash** [comment]
@jshiller It means the network has signaled its interest in unifying through a token swap. Next a proposal will be released that details the minting requirements, explains the technical means for achieving the swap, and explanation for chosen rate.

**Comment by jshiller** [comment]
@moonstash thanks for the explanation. Any idea when the next proposal will be released? Once the swap details have been worked out, how likely is it that Binance will automatically swap ENG for SCRT?

**Comment by moonstash** [comment]
I have no ETA for you at the moment but we are actively working on it. In the meantime if you want to stay up to date on proposals you can join this telegram room. Understand this room is not exclusively about the token swap.

This room is for discussions around governance, proposals, and enigma politics.
https://t.me/SecretDAO

**Comment by mohammedpatla** [comment]
After some thinking and feedback, I change my view to a 1:10(ENG: SCRT) swap.
I think a 1:10 swap is NOT bad either since the economics are being rebuilt anyway.
I think a 1:10 a good idea because 
1) By making the pool bigger we reduce all the initial minted token value and decide on how much should be further minted for the team/validators/pool during this process.
2) Inflation can be reduced initially as the number of tokens rewarded would be the same( But the Value of the token might be less compared to fiat)
3) Give the community more power of choosing validators for the network, due to stronger SCRT power for the community.

**Comment by moonstash** [comment]
Hey thanks for the update @mohammedpatla. I am just curious what your thoughts are on a 1:10 rate knowing that would essentially dilute the existing supply to a point where the Enigma team would have 1/10th of what they'd have with a 1:1 swap?

I think the future of the network depends on the ability for future development to be funded well into the future.

**Comment by mohammedpatla** [comment]
@moonstash 
Well as far as development is concerned, I agree, we as a community need to compensate them well for proper development. And hence the DAO pool should be used for those purposes since there are going to be proposals set in place for every update to the network, those proposals should come with a reward pool for that.

I am NOT gonna even talk about the funds raised by the core team for the same development of the network 45Mill that they should still hold partially(That they and the SEC are figuring out). Since most of the ENG is gonna be burned on SWAP it would be unfair for a team to hold on to initial funds AND have such a big stake in the network as just developers (Or even core-team). 

Since now the enigma network is community-owned, that means that the community should be rewarded for taking the initiative to for monitoring the network. And the excess minted tokens should be held in a treasury. 

Yes, the initial supply of the tokens for the developers would be reduced( What they have currently can be contributed as initial genesis benefits), but for there continued efforts they should be rewarded from an Enigma network treasury for every network update they implement (Rather than hold the lump sum from the beginning).

This is my proposed alternative for all Validators and the community to consider since we are moving the enigma network towards governance and DAO.

**Comment by moonstash** [comment]
@mohammedpatla 
Thanks for adding context :)

**Comment by silkyjohnson1** [comment]
@mohammedpatla I do like the idea of rewarding them for work accomplished... but i mean people have to be paid salary on an ongoing basis.  So they're going to need SCRT to sell for $$$.  We can't just dangle money out like a carrot, and who knows how much they'll have left over after SEC settlement, and who knows how much they have left (maybe very little).

If we lose the team, we lose ENG.

**Comment by mohammedpatla** [comment]
@silkyjohnson1 
I agree, but we can set it so when a proposal is selected we can give them 50% payment upfront or in escrow that is rewarded monthly for example.

And yes I don't think anyone knows how much assets the ENG team has after refunds, but if you think about it not all ENG are gonna be refundable and the ones that do qualify have to be in the US with the requirements. So, in my opinion, I would say less than 25% of them are eligible for a refund, which means they should still have 75% of the assets. But still, that's just shooting in the dark.

**Comment by edlanes** [comment]
100% agree with the 1:10 proposal.

Instead of trying to guess how much money the team has left from the ICO and award them with a large sum, the Enigma team could ask the DAO for money to fund specific features.

**Comment by edlanes** [comment]
Also, let's get one thing straight here. **Only 1-2 validators are pushing the narrative that the community wants a 1:1 swap**. There's a **very clear conflict of interest** here as a lower ratio is ONLY in the best interest of the current validators and the team. Community would be happy with any higher ratio as they don't have any existing free SCRT tokens that would get devalued.

**Comment by moonstash** [comment]
After 2+ weeks of discussion from this proposal we've already collected the feedback from here for our proposal and are proceeding with 1:1. Other technical details can be discussed in the new thread. Thank you to everyone who gave feedback. :) 

We understand there is a vocal minority trying to drag this process out. I encourage people to give feedback as we ask for it, there will be plenty of time to give feedback on each part of our proposal. 

Next part of the discussion.
https://github.com/secretnodes/secretnodes.org/issues/15
