### ISSUE TITLE
Burn ENG for SCRT! Draft Proposal

### ISSUE THREAD

**Issue by moonstash** [secretnodes/secretnodes.org#15]
Burn ENG for SCRT! Draft proposal (Links updated to v1.0 on 3/7/2020)
https://github.com/secretnodes/secretnodes.org/blob/master/docs/papers/Burn_ENG_for_SCRT-v1.pdf

Milestones  Project Tracking
https://github.com/secretnodes/secretnodes.org/blob/master/docs/papers/Burn_ENG_for_SCRT_Milestones-v1.pdf

Please give all feedback you wish to be considered on this github issue.

Note : The 1:1 rate is already decided on based on feedback from the community during a 2+ week time frame. We've accounted for as many of the needs of all 3 stakeholders as possible (The community of holders, the team, and the validators.) If you support another rate then you will have to proceed with your own proposal.

This discussion will be open for a minimum of 2 weeks.

**Comment by mohammedpatla** [comment]
I like that you have thought of some of the details!!
Once completed I am assuming you going to put this as a proposal on-chain for validators to vote on before the start of the project? Would the voting not take time as I see some things have already been started to be worked on?
Or would this proposal only be for the ENG community?

**Comment by moonstash** [comment]
@mohammedpatla The technical aspects of the plan are already underway. We will have an updated plan on chain in the near future.

**Comment by levackt** [comment]
Is the contract and relayer based on [Peggy](https://github.com/cosmos/peggy)?

**Comment by moonstash** [comment]
@levackt No. Not based on Peggy.

**Comment by moonstash** [comment]
We have moved out of the draft and uploaded the "Burn ENG for SCRT!" Proposal to the Enigma Blockchain. All documents and locations for discussions can be found in the proposal on chain.

On chain link : https://explorer.mainnet.enigma.co/proposals/4

**Comment by moonstash** [comment]
Conversation continued here https://github.com/secretnodes/secretnodes.org/issues/16

**Comment by moonstash** [comment]
https://github.com/secretnodes/secretnodes.org/issues/16
