### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by lauraweindorf** [secretnodes/secretnodes.org#7]
**Broken links in README**
The `docs` part of the path is missing for a couple of links in the readme.

**To Reproduce**
1. Go to `https://github.com/secretnodes/secretnodes.org/blob/master/docs/readme.md`
2. Click on _Jump right in and start learning!_ link text
3. See 404 error page

Same observed for _Genesis Games Overview_ link text under the *Announcements section*.

May be true for other `docs/*.md` files if they reference secret node documentation.

**Expected behavior**
Navigation should work.

**Screenshots**

**Desktop (please complete the following information):**
 - Device: [e.g. NUC + Model Number / What device are you using?]
Desktop PC
 - OS: [e.g. Operating System + Version]
Windows 10

**Additional context**
none

**Comment by lauraweindorf** [comment]
See _please read this information thoroughly_ on:

`https://github.com/secretnodes/secretnodes.org/blob/master/docs/nodes-quickstart.md`

**Comment by moonstash** [comment]
Hey Laura, thanks for taking the time to go over the codebase for the site! When you try to visit that link from the github view it does result in a 404 page but if you view the content from the site the link works!

Live Link for readme
https://secretnodes.org/#/README

Live Link for Node Quickstart
https://secretnodes.org/#/nodes-quickstart?id=enigma-nodes-overview

I've gone ahead and updated those links so now it should work both on the live site and when visiting the links via github. Thanks again!
